// components/app/SpeechBar.vue
<template>
  <!-- Sasonica: the voice's player, on every page. Speech is played by this
       app's speech listener (com.audiobookshelf.app.speech), but what to
       play next — the reply queue, the turns, the sentences — is red5's, so
       the controls go there: this asks the canvas what is being said
       (/speech/now) and sends the tmux popup's listening keys back
       (/speech/ctl). Collapsed it sits in the mini player's place; a tap opens
       the full set. Fork-only file. -->
  <div>
    <div v-if="visible" id="speechBar" class="fixed left-0 right-0 z-50 pointer-events-none" :style="{ bottom: bottomPx + 'px', height: barHeightPx + 'px' }">
      <div class="speech-bar w-full h-full flex items-center px-3 pointer-events-auto bg-primary border-t border-fg/10" @click="expand">
        <span class="material-symbols text-xl text-fg-muted mr-2" :class="{ 'speech-pulse': now.speaking }">graphic_eq</span>
        <div class="flex-grow min-w-0">
          <p class="text-sm font-semibold text-fg truncate">{{ now.title || 'Speaking' }}</p>
          <p class="text-xs text-fg-muted truncate">{{ now.sentence || (now.paused ? 'Paused' : '…') }}</p>
        </div>
        <button class="material-symbols text-2xl text-fg px-2" aria-label="Back a sentence" @click.stop="ctl('skip-')">fast_rewind</button>
        <button class="material-symbols text-3xl text-fg px-1" :aria-label="now.paused ? 'Resume' : 'Pause'" @click.stop="toggle">{{ now.paused ? 'play_arrow' : 'pause' }}</button>
        <button class="material-symbols text-2xl text-fg px-2" aria-label="Next sentence" @click.stop="ctl('skip+')">fast_forward</button>
      </div>
    </div>

    <!-- The full player: every key the popup has for a listener. It stays
         open when the reply ends, so replay and the older turns are still to
         hand — which is when they are wanted. -->
    <div v-if="expanded" class="fixed inset-0 flex flex-col justify-end" style="z-index: 60" @click.self="expanded = false">
      <div class="absolute inset-0 bg-black/50" @click="expanded = false" />
      <div class="speech-sheet relative w-full bg-primary border-t border-fg/10 rounded-t-xl px-4 pt-2 pb-6">
        <div class="flex items-center">
          <span class="material-symbols text-xl text-fg-muted mr-2" :class="{ 'speech-pulse': now.speaking }">graphic_eq</span>
          <p class="flex-grow min-w-0 text-base font-semibold truncate" :class="now.item ? 'underline' : ''" @click="open">{{ now.title || (now.live ? 'Speaking' : 'Nothing playing') }}</p>
          <button class="material-symbols text-3xl text-fg-muted pl-2" aria-label="Close" @click="expanded = false">expand_more</button>
        </div>
        <p class="text-sm text-fg min-h-[3.75rem] line-clamp-3 mt-2 mb-3">{{ now.sentence || (now.paused ? 'Paused' : now.live ? '…' : 'The last reply has finished. Replay it, or go back a turn.') }}</p>

        <div class="flex items-center justify-between">
          <button class="speech-key" aria-label="Previous turn" @click="prevTurn"><span class="material-symbols text-3xl">skip_previous</span></button>
          <button class="speech-key" aria-label="Back a paragraph" @click="ctl('para-')"><span class="material-symbols text-3xl">keyboard_double_arrow_left</span></button>
          <button class="speech-key" aria-label="Back a sentence" @click="ctl('skip-')"><span class="material-symbols text-3xl">fast_rewind</span></button>
          <button class="speech-key speech-key-main" :aria-label="now.paused ? 'Resume' : 'Pause'" @click="toggle"><span class="material-symbols text-4xl fill">{{ now.paused || !now.live ? 'play_arrow' : 'pause' }}</span></button>
          <button class="speech-key" aria-label="Next sentence" @click="ctl('skip+')"><span class="material-symbols text-3xl">fast_forward</span></button>
          <button class="speech-key" aria-label="Next paragraph" @click="ctl('para+')"><span class="material-symbols text-3xl">keyboard_double_arrow_right</span></button>
          <button class="speech-key" aria-label="Next turn" @click="nextTurn"><span class="material-symbols text-3xl">skip_next</span></button>
        </div>

        <div class="flex items-center justify-between mt-4">
          <button class="speech-pill" @click="replayLatest"><span class="material-symbols text-lg mr-1">replay</span>Replay latest</button>
          <button class="speech-pill" :disabled="!now.live" @click="ctl('jump-end')"><span class="material-symbols text-lg mr-1">last_page</span>End of reply</button>
          <button class="speech-pill" :class="now.muted ? 'text-warning' : ''" @click="ctl('mute')"><span class="material-symbols text-lg mr-1">{{ now.muted ? 'volume_off' : 'volume_mute' }}</span>Mute</button>
        </div>

        <div class="flex items-center mt-4">
          <p class="text-xs text-fg-muted w-16">Speed</p>
          <button class="speech-key" aria-label="Slower" @click="ctl('speed-')"><span class="material-symbols text-2xl">remove</span></button>
          <button class="flex-grow text-center text-sm font-mono" aria-label="Reset speed" @click="ctl('speed0')">{{ speedLabel }}</button>
          <button class="speech-key" aria-label="Faster" @click="ctl('speed+')"><span class="material-symbols text-2xl">add</span></button>
        </div>
        <div class="flex items-center mt-2">
          <p class="text-xs text-fg-muted w-16">Volume</p>
          <button class="speech-key" aria-label="Quieter" @click="ctl('vol-')"><span class="material-symbols text-2xl">volume_down</span></button>
          <div class="flex-grow" />
          <button class="speech-key" aria-label="Louder" @click="ctl('vol+')"><span class="material-symbols text-2xl">volume_up</span></button>
        </div>
      </div>
    </div>
  </div>
</template>

<script>
// How often to ask. Quick while a voice is live, so the sentence keeps up and
// the bar goes away soon after the reply ends; slow while quiet, which is most
// of the time. Nothing at all while the app is not on screen.
const POLL_LIVE_MS = 1500
const POLL_IDLE_MS = 5000
const POLL_FAILING_MS = 15000
const BAR_HEIGHT_PX = 56
// The collapsed mini player's height (.playerContainer in AudioPlayer.vue).
const MINI_PLAYER_PX = 120

export default {
  data() {
    return {
      baseUrl: '',
      now: { live: false },
      timer: null,
      failing: false,
      expanded: false,
      // Which reply the turn keys are on, as the popup's hist_idx: 1 is the
      // latest. red5 answers `prev` with where it landed.
      histIdx: 1
    }
  },
  computed: {
    miniPlayerShowing() {
      return this.$store.getters['getIsPlayerOpen'] && !this.$store.state.playerIsHidden
    },
    bottomPx() {
      return this.miniPlayerShowing ? MINI_PLAYER_PX : 0
    },
    barHeightPx() {
      return BAR_HEIGHT_PX
    },
    speedLabel() {
      const v = Number(this.now.speed)
      return v ? `${v.toFixed(2).replace(/0$/, '')}×` : '1×'
    },
    // Everywhere but over the full-screen player — the conversation's own page
    // included: it follows the words, but the bar is the only player speech
    // has in this app, and tapping the bar lands there.
    visible() {
      return !!this.now.live && !this.$store.state.playerIsFullscreen
    }
  },
  watch: {
    // Room for the bar: pages size themselves to #content, so the bar takes
    // its height out of #content rather than covering the page's last row.
    visible: {
      immediate: true,
      handler(on) {
        document.documentElement.style.setProperty('--speech-bar-height', on ? BAR_HEIGHT_PX + 'px' : '0px')
      }
    }
  },
  methods: {
    request(method, path, data) {
      const token = this.$store.getters['user/getToken']
      return this.$nativeHttp.request(method, `${this.baseUrl}${path}`, data, {
        headers: { Authorization: `Bearer ${token}` }
      })
    },
    async poll() {
      if (!this.$store.getters['user/getToken']) return
      // Asked here, not once at mount: the layout mounts before the server
      // connection is restored, and the address is derived from it, so a
      // mount-time answer is '' and stays '' for the life of the app.
      if (!this.baseUrl) {
        this.baseUrl = await this.$localStore.agentMediaBaseUrl(this.$store.state.user.serverConnectionConfig?.address)
        if (!this.baseUrl) return
      }
      try {
        const res = await this.request('GET', '/speech/now')
        this.now = res && res.ok ? res : { live: false }
        this.failing = false
      } catch (error) {
        // No canvas, not allowed, or the network blinked: no bar, and ask
        // less often until it answers again.
        this.now = { live: false }
        this.failing = true
      }
    },
    nextDelay() {
      if (this.failing) return POLL_FAILING_MS
      return this.now.live ? POLL_LIVE_MS : POLL_IDLE_MS
    },
    startPolling() {
      if (this.timer) return
      const tick = async () => {
        this.timer = null
        await this.poll()
        if (!document.hidden) this.timer = window.setTimeout(tick, this.nextDelay())
      }
      this.timer = window.setTimeout(tick, 0)
    },
    stopPolling() {
      if (!this.timer) return
      window.clearTimeout(this.timer)
      this.timer = null
    },
    onVisibilityChange() {
      if (document.hidden) this.stopPolling()
      else this.startPolling()
    },
    async ctl(action, arg) {
      let res = null
      try {
        res = await this.request('POST', '/speech/ctl', arg ? { action, arg } : { action })
      } catch (error) {
        console.error('[SpeechBar] ctl failed', action, error?.message || error)
      }
      // The server's answer is the truth; ask for it straight away rather
      // than at the next tick.
      this.stopPolling()
      window.setTimeout(() => this.startPolling(), 300)
      return res
    },
    expand() {
      this.histIdx = 1
      this.expanded = true
    },
    // The popup's <: a restart first when well into a turn, else the older
    // turn. red5 prints the turn it chose, so the next press starts there.
    async prevTurn() {
      const res = await this.ctl('prev', this.histIdx)
      const n = parseInt(String(res?.out || '').trim(), 10)
      if (n > 0) this.histIdx = n
    },
    // The popup's >: a newer turn while going back through them, and the end
    // of the reply once at the latest.
    nextTurn() {
      if (this.histIdx > 1) {
        this.histIdx -= 1
        this.ctl('replay', this.histIdx)
      } else {
        this.ctl('jump-end')
      }
    },
    replayLatest() {
      this.histIdx = 1
      this.ctl('replay', 1)
    },
    toggle() {
      // Nothing playing: the button means the popup's r, not a pause.
      if (!this.now.live) return this.replayLatest()
      this.now = { ...this.now, paused: !this.now.paused } // the icon answers the thumb at once
      this.ctl('toggle')
    },
    open() {
      if (!this.now.item) return
      this.expanded = false
      this.$router.push(`/item/${this.now.item}`)
    }
  },
  mounted() {
    document.addEventListener('visibilitychange', this.onVisibilityChange)
    this.startPolling()
  },
  beforeDestroy() {
    this.stopPolling()
    document.removeEventListener('visibilitychange', this.onVisibilityChange)
    document.documentElement.style.setProperty('--speech-bar-height', '0px')
  }
}
</script>

<style>
/* Sasonica: global on purpose — #content belongs to the layout. The bar's
   height comes out of the page's box (border-box), so the page's own
   scrollers end above the bar instead of under it. */
#content {
  padding-bottom: var(--speech-bar-height, 0px);
}
</style>

<style scoped>
.speech-bar {
  height: 56px;
  box-shadow: 0px -4px 8px #11111133;
}
.speech-sheet {
  box-shadow: 0px -4px 16px #11111155;
}
.speech-key {
  display: flex;
  align-items: center;
  justify-content: center;
  width: 2.75rem;
  height: 2.75rem;
  border-radius: 9999px;
}
.speech-key-main {
  width: 3.5rem;
  height: 3.5rem;
  background: rgba(255, 255, 255, 0.12);
}
.speech-pill {
  display: flex;
  align-items: center;
  font-size: 0.8rem;
  padding: 0.4rem 0.75rem;
  border-radius: 9999px;
  border: 1px solid rgba(255, 255, 255, 0.15);
}
.speech-pill:disabled {
  opacity: 0.4;
}
.speech-pulse {
  animation: speech-pulse 1.2s ease-in-out infinite;
}
@keyframes speech-pulse {
  0%,
  100% {
    opacity: 1;
  }
  50% {
    opacity: 0.4;
  }
}
</style>

// chat/app/components/SpeechBar.tsx
/**
 * The voice's player, on every screen (Sasonica's SpeechBar.vue, ported).
 *
 * Collapsed, it is one row: what is being said (the conversation's title —
 * tap to open it — over the current sentence), a progress sliver along its
 * top edge from `pos`/`dur`, and the keys wanted most: back a sentence,
 * pause/resume, on a sentence. The chevron (or a tap on the sentence) opens
 * the full set in a sheet: turns, paragraphs, end of reply, replay, speed,
 * volume and mute — every key the canvas takes from the app (§6.5).
 *
 * In the thread that is speaking, the live line already bolds the sentence,
 * so the bar leaves it out and says only the time (or "Paused" and the time).
 *
 * Shown while a reply is live (speaking or paused); a reply that has just
 * ended keeps it for 30 s, since that is when replay is wanted. The first
 * FULL_HINT_TIMES times on a device that says "Finished · play to hear it
 * again"; after that it is just the title and a compact "▶ Replay" key.
 * State and keys come from the one SpeechProvider poll.
 */
import { useEffect, useRef, useState, type ReactNode } from 'react'
import { createPortal } from 'react-dom'
import { useNavigate } from 'react-router'
import type { SessionId } from '../api/types'
import { useSpeech } from '../hooks/useSpeech'
import { useTitle } from '../lib/titles'

// ── Icons (currentColor, sized by the button's font-size) ─────────────────

const Svg = ({ children, label }: { children: ReactNode; label?: string }) => (
  <svg className="ico" viewBox="0 0 24 24" aria-hidden={label ? undefined : true} role={label ? 'img' : undefined} aria-label={label}>
    {children}
  </svg>
)
export const IconPlay = () => (
  <Svg>
    <path d="M8 5.5v13a1 1 0 0 0 1.5.86l10.2-6.5a1 1 0 0 0 0-1.72L9.5 4.64A1 1 0 0 0 8 5.5z" fill="currentColor" />
  </Svg>
)
export const IconPause = () => (
  <Svg>
    <rect x="6" y="5" width="4" height="14" rx="1" fill="currentColor" />
    <rect x="14" y="5" width="4" height="14" rx="1" fill="currentColor" />
  </Svg>
)
export const IconReplay = () => (
  <Svg>
    <path d="M12 5V2L7 6l5 4V7a6 6 0 1 1-6 6H4a8 8 0 1 0 8-8z" fill="currentColor" />
  </Svg>
)
const IconBackSentence = () => (
  <Svg>
    <path d="M11 18V6l-8.5 6L11 18zm.5-6 8.5 6V6l-8.5 6z" fill="currentColor" />
  </Svg>
)
const IconFwdSentence = () => (
  <Svg>
    <path d="M4 18l8.5-6L4 6v12zm9-12v12l8.5-6L13 6z" fill="currentColor" />
  </Svg>
)
const IconPrevTurn = () => (
  <Svg>
    <path d="M6 6h2v12H6zm3.5 6 8.5 6V6z" fill="currentColor" />
  </Svg>
)
const IconNextTurn = () => (
  <Svg>
    <path d="M6 18l8.5-6L6 6v12zM16 6v12h2V6h-2z" fill="currentColor" />
  </Svg>
)
const IconParaBack = () => (
  <Svg>
    <path d="M17.6 6.4 16.2 5l-7 7 7 7 1.4-1.4L12 12zm-6 0L10.2 5l-7 7 7 7 1.4-1.4L6 12z" fill="currentColor" />
  </Svg>
)
const IconParaFwd = () => (
  <Svg>
    <path d="M6.4 6.4 7.8 5l7 7-7 7-1.4-1.4L12 12zm6 0L13.8 5l7 7-7 7-1.4-1.4L18 12z" fill="currentColor" />
  </Svg>
)
const IconEnd = () => (
  <Svg>
    <path d="M5.6 7.4 7 6l6 6-6 6-1.4-1.4L10.2 12zM16 6h2v12h-2z" fill="currentColor" />
  </Svg>
)
const IconExpand = ({ open }: { open: boolean }) => (
  <Svg>
    <path d={open ? 'M7.4 8.6 12 13.2l4.6-4.6L18 10l-6 6-6-6z' : 'M7.4 15.4 12 10.8l4.6 4.6L18 14l-6-6-6 6z'} fill="currentColor" />
  </Svg>
)
const IconVolume = ({ muted }: { muted: boolean }) => (
  <Svg>
    <path d="M4 9v6h4l5 5V4L8 9H4z" fill="currentColor" />
    {muted ? (
      <path d="m16 9 5 6m0-6-5 6" stroke="currentColor" strokeWidth="2" strokeLinecap="round" fill="none" />
    ) : (
      <path d="M16 8.5a5 5 0 0 1 0 7M18.5 6a8.5 8.5 0 0 1 0 12" stroke="currentColor" strokeWidth="2" strokeLinecap="round" fill="none" />
    )}
  </Svg>
)

// ── Helpers ───────────────────────────────────────────────────────────────

function clock(s: number | null | undefined): string {
  if (s == null || !isFinite(s)) return ''
  const t = Math.max(0, Math.round(s))
  return `${Math.floor(t / 60)}:${String(t % 60).padStart(2, '0')}`
}

function speedLabel(v: number | null | undefined): string {
  const n = Number(v)
  return n ? `${n.toFixed(2).replace(/\.?0+$/, '')}×` : '1×'
}

/** 0–1, or null when the server gave no position. */
function progressOf(pos: number | null | undefined, dur: number | null | undefined): number | null {
  if (pos == null || !dur) return null
  return Math.max(0, Math.min(1, pos / dur))
}

// ── The finished hint, first few times only ───────────────────────────────

/** How many times the long "Finished · play to hear it again" is shown, per device. */
const FULL_HINT_TIMES = 3
const HINT_KEY = 'sasonica.chat.finishedHints'
/** The finished replies already counted in this page load (a bar per screen, one count each). */
const counted = new Map<number, boolean>()

/**
 * Whether this finished reply (`endedAt`) gets the full hint. Decided once
 * per reply and remembered, so every bar that shows it agrees; storage
 * blocked means the hint shows every time (never an error).
 */
function fullHintFor(endedAt: number): boolean {
  const known = counted.get(endedAt)
  if (known !== undefined) return known
  let seen = 0
  try {
    seen = Number(window.localStorage.getItem(HINT_KEY)) || 0
  } catch {
    counted.set(endedAt, true)
    return true
  }
  const full = seen < FULL_HINT_TIMES
  if (full) {
    try {
      window.localStorage.setItem(HINT_KEY, String(seen + 1))
    } catch {
      // Not remembered; shown again next time.
    }
  }
  counted.set(endedAt, full)
  return full
}

/** A tap on the bar's title sooner than this after it appeared or changed thread is ignored. */
const SETTLE_TAP_MS = 800

// ── The bar ───────────────────────────────────────────────────────────────

export function SpeechBar({ here }: { here?: SessionId }) {
  const speech = useSpeech()
  const { now, finished, error } = speech
  const [open, setOpen] = useState(false)
  const navigate = useNavigate()

  const live = !!now?.live
  const visible = live || !!finished || open
  // Hand the sheet back when the bar goes (no reply, nothing just ended).
  useEffect(() => {
    if (!live && !finished) setOpen(false)
  }, [live, finished])

  const session = live ? now?.session : finished?.session
  const title = useTitle(session, (live ? now?.title : finished?.title) || '') || (live ? 'Speaking' : 'Nothing playing')
  // When the bar appeared or changed thread. A tap this soon after was
  // aimed at whatever the bar just pushed aside, not at the bar.
  const changedAtRef = useRef(0)
  useEffect(() => {
    changedAtRef.current = Date.now()
  }, [session, visible])

  if (!visible) return null

  const paused = live ? !!now?.paused : true
  const inHere = !!here && session === here
  const progress = live ? progressOf(now?.pos, now?.dur) : null
  const times = live && now?.pos != null ? `${clock(now.pos)}${now.dur ? ` / ${clock(now.dur)}` : ''}` : ''

  const openThread = () => {
    if (!session || inHere || Date.now() - changedAtRef.current < SETTLE_TAP_MS) return
    setOpen(false)
    navigate(`/t/${encodeURIComponent(session)}`, { state: { title } })
  }
  const expand = () => {
    speech.resetTurns()
    setOpen(true)
  }

  // Finished: the long hint the first few times, then nothing but the key.
  const compact = !live && !error && !!finished && !fullHintFor(finished.endedAt)
  const second = error
    ? error
    : !live
      ? compact
        ? ''
        : 'Finished · play to hear it again'
      : inHere
        ? // Short: the keys take most of the row, and the dot says "speaking".
          paused ? `Paused${times ? ` · ${times}` : ''}` : times || 'Speaking'
        : now?.sentence || (paused ? 'Paused' : '…')

  const toggleLabel = !live ? 'Replay' : paused ? 'Resume' : 'Pause'

  return (
    <>
      <div className={`speech-bar${inHere ? ' here' : ''}${paused ? ' paused' : ''}${compact ? ' compact' : ''}`} role="region" aria-label="Speech">
        {progress !== null && (
          <div className="speech-progress" aria-hidden="true">
            <i style={{ width: `${progress * 100}%` }} />
          </div>
        )}
        <div className="speech-text">
          {inHere ? (
            // This thread is the one speaking: its live line has the words.
            <button className="speech-title" onClick={expand}>
              <span className={live && !paused ? 'eq on' : 'eq'} aria-hidden="true" />
              {second}
            </button>
          ) : (
            <>
              {/* In a thread, another thread's reply opens the sheet (which has
                  the link): the bar changes under the reader's thumb when a
                  reply starts elsewhere, and a stray tap must never take
                  them away from what they are reading. On the list, a tap
                  opens it. */}
              <button className="speech-title" onClick={session && !here ? openThread : expand} title={session && !here ? 'Open this conversation' : undefined}>
                <span className={live && !paused ? 'eq on' : 'eq'} aria-hidden="true" />
                {title}
              </button>
              {second && (
                <button className={error ? 'speech-sentence failed' : 'speech-sentence'} onClick={expand}>
                  {second}
                </button>
              )}
            </>
          )}
        </div>
        {live && (
          <button className="skey" aria-label="Back a sentence" onClick={() => void speech.ctl('skip-')}>
            <IconBackSentence />
          </button>
        )}
        {compact ? (
          <button className="skey main replay-pill" aria-label="Replay" onClick={speech.toggle}>
            <IconPlay /> <span>Replay</span>
          </button>
        ) : (
          <button className="skey main" aria-label={toggleLabel} aria-pressed={live ? !paused : undefined} onClick={speech.toggle}>
            {!live ? <IconReplay /> : paused ? <IconPlay /> : <IconPause />}
          </button>
        )}
        {live && (
          <button className="skey" aria-label="Next sentence" onClick={() => void speech.ctl('skip+')}>
            <IconFwdSentence />
          </button>
        )}
        <button className="skey more" aria-label="All speech controls" aria-expanded={open} onClick={() => (open ? setOpen(false) : expand())}>
          <IconExpand open={open} />
        </button>
      </div>
      {open && typeof document !== 'undefined' && createPortal(<SpeechSheet title={title} session={session || null} inHere={inHere} onOpen={openThread} onClose={() => setOpen(false)} />, document.body)}
    </>
  )
}

// ── The full set ──────────────────────────────────────────────────────────

function SpeechSheet(props: { title: string; session: SessionId | null; inHere: boolean; onOpen: () => void; onClose: () => void }) {
  const speech = useSpeech()
  const { now, error } = speech
  const live = !!now?.live
  const paused = live ? !!now?.paused : true
  const progress = live ? progressOf(now?.pos, now?.dur) : null

  useEffect(() => {
    const onKey = (e: KeyboardEvent) => e.key === 'Escape' && props.onClose()
    window.addEventListener('keydown', onKey)
    return () => window.removeEventListener('keydown', onKey)
  }, [props])

  const sentence = error || now?.sentence || (paused && live ? 'Paused' : live ? '…' : 'The last reply has finished. Replay it, or go back a turn.')

  return (
    <div className="speech-sheet-wrap" onClick={props.onClose}>
      <div className="speech-sheet" role="dialog" aria-label="Speech controls" onClick={(e) => e.stopPropagation()}>
        <div className="sheet-head">
          <span className={live && !paused ? 'eq on' : 'eq'} aria-hidden="true" />
          {props.session && !props.inHere ? (
            <button className="sheet-title link" onClick={props.onOpen}>
              {props.title}
            </button>
          ) : (
            <p className="sheet-title">{props.title}</p>
          )}
          <button className="skey" aria-label="Close" onClick={props.onClose}>
            <IconExpand open />
          </button>
        </div>

        <div className="sheet-cols">
          <div className="sheet-col">
            <p className={error ? 'sheet-sentence failed' : 'sheet-sentence'}>{sentence}</p>
            <div className="sheet-progress">
              <div className="speech-progress inline" aria-hidden="true">
                <i style={{ width: `${(progress ?? 0) * 100}%` }} />
              </div>
              <span className="sheet-time">{live ? `${clock(now?.pos)}${now?.dur ? ` / ${clock(now.dur)}` : ''}` : ''}</span>
            </div>
            <div className="transport">
              <button className="skey" aria-label="Previous turn" onClick={speech.prevTurn}>
                <IconPrevTurn />
              </button>
              <button className="skey" aria-label="Back a paragraph" disabled={!live} onClick={() => void speech.ctl('para-')}>
                <IconParaBack />
              </button>
              <button className="skey" aria-label="Back a sentence" disabled={!live} onClick={() => void speech.ctl('skip-')}>
                <IconBackSentence />
              </button>
              <button className="skey main big" aria-label={!live ? 'Replay' : paused ? 'Resume' : 'Pause'} onClick={speech.toggle}>
                {paused ? <IconPlay /> : <IconPause />}
              </button>
              <button className="skey" aria-label="Next sentence" disabled={!live} onClick={() => void speech.ctl('skip+')}>
                <IconFwdSentence />
              </button>
              <button className="skey" aria-label="Next paragraph" disabled={!live} onClick={() => void speech.ctl('para+')}>
                <IconParaFwd />
              </button>
              <button className="skey" aria-label={speech.histIdx > 1 ? 'Next turn' : 'End of reply'} onClick={speech.nextTurn}>
                <IconNextTurn />
              </button>
            </div>
          </div>

          <div className="sheet-col">
            <div className="pills">
              <button className="pill" onClick={speech.replayLatest}>
                <IconReplay /> Replay latest
              </button>
              <button className="pill" disabled={!live} onClick={() => void speech.ctl('jump-end')}>
                <IconEnd /> End of reply
              </button>
              <button className={now?.muted ? 'pill on' : 'pill'} aria-pressed={!!now?.muted} onClick={() => void speech.ctl('mute')}>
                <IconVolume muted={!!now?.muted} /> {now?.muted ? 'Muted' : 'Mute'}
              </button>
            </div>
            <div className="knob">
              <span className="knob-label">Speed</span>
              <button className="skey" aria-label="Slower" onClick={() => void speech.ctl('speed-')}>
                −
              </button>
              <button className="knob-value" aria-label="Reset speed to 1×" title="Reset to 1×" onClick={() => void speech.ctl('speed0')}>
                {speedLabel(now?.speed)}
              </button>
              <button className="skey" aria-label="Faster" onClick={() => void speech.ctl('speed+')}>
                +
              </button>
            </div>
            <div className="knob">
              <span className="knob-label">Volume</span>
              <button className="skey" aria-label="Quieter" onClick={() => void speech.ctl('vol-')}>
                −
              </button>
              <span className="knob-value quiet" aria-hidden="true">
                <IconVolume muted={!!now?.muted} />
              </span>
              <button className="skey" aria-label="Louder" onClick={() => void speech.ctl('vol+')}>
                +
              </button>
            </div>
          </div>
        </div>
      </div>
    </div>
  )
}
